apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: rbeecham
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/rbeecham-harbor-project/app@sha256:a10fdd1d07a5f9a23a33a0664a31f510c30ab455db1a9b0ba2a15c4802e7596c
        ports:
        - containerPort: 5000
